matrix:
    NODE_VERSION:
        - 5
        - 4
        - latest
build:
    image: node:$$NODE_VERSION
    commands:
        - echo "Installing latest stable npm version..."
        - npm install -g npm@latest
        - npm --version
        - npm install -g gulp
        - gulp test
